### ISSUE TITLE
Software itemType

### ISSUE THREAD

**Issue by Mjvolk3** [urschrei/pyzotero#158]
Could you support the `software` itemType? From looking at the tested [item_types.json](https://github.com/urschrei/pyzotero/blob/82af4a7d6fbfb34f6dab0337e6d54185bbe42e43/tests/api_responses/item_types.json) it doesn't look supported. Thanks!

**Comment by Mjvolk3** [comment]
Could you also support `preprint`?

**Comment by urschrei** [comment]
Available item types are governed by the return value of the  [Zotero API `/itemTypes`](https://www.zotero.org/support/dev/web_api/v3/types_and_fields) call and retrieved using `pyzotero.item_types()`. Currently, `Software` is the localized string of the `computerProgram` item type and `Preprint` is the localized string of the `preprint` item type.[ When retrieving an item template in order to create new items you have to specify the `itemType`, not the localized string](https://pyzotero.readthedocs.io/en/latest/#zotero.Zotero.item_template).

As per the issue template, please provide context and concrete data about what you're trying to do and what went wrong when you tried to do it, otherwise I have to try to infer whether there's a bug or a misunderstanding, which can be an unreliable process…
